# Generated by Django 4.2.6 on 2023-10-18 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=100)),
                ('laboratorio', models.CharField(max_length=100)),
                ('dispositivo', models.CharField(max_length=100)),
                ('identificacao_dispositivo', models.CharField(max_length=50)),
                ('especificacoes_tecnicas', models.TextField()),
                ('data_aquisicao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Falha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=100)),
                ('laboratorio', models.CharField(max_length=100)),
                ('tipo_manutencao', models.CharField(max_length=50)),
                ('identificacao_dispositivo', models.CharField(max_length=50)),
                ('descricao_falha', models.TextField()),
                ('data_ocorrencia', models.DateField()),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meu_app.cadastrodispositivo')),
            ],
        ),
    ]
